name: Build Docker Image

# on:
#   release:
#     types:
#       - published

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Download gatesentry-linux binary from latest release
        run: |
          wget $(curl -s https://api.github.com/repos/fifthsegment/Gatesentry/releases/latest | jq -r '.assets[] | select(.name == "gatesentry-linux") | .browser_download_url')

      - name: Create Dockerfile
        run: |
          echo 'FROM ubuntu:latest' > Dockerfile
          echo 'COPY gatesentry-linux /usr/local/bin/gatesentry-linux' >> Dockerfile
          echo 'RUN chmod +x /usr/local/bin/gatesentry-linux' >> Dockerfile
          echo 'EXPOSE 80 53 10413 10786' >> Dockerfile
          echo 'CMD ["/usr/local/bin/gatesentry-linux"]' >> Dockerfile

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          #   tags: abdullahi1/gatesentry:${{ github.event.release.tag_name }}
          tags: abdullahi1/gatesentry:latest
