name: Bump Version
on:
  push:
    branches:
      - release-*

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Bump version in main.go
        id: bump-version
        run: |
          VERSION=$(awk -F'"' '/var GATESENTRY_VERSION =/ { print $2 }' main.go)
          echo "Extracted Version: $VERSION"

          IFS='.' read -r -a VERSION_ARRAY <<< "$VERSION"
          echo "Version Array: ${VERSION_ARRAY[@]}"

          NEW_MINOR=$(( ${VERSION_ARRAY[1]} + 1 ))
          echo "New Minor: $NEW_MINOR"

          NEW_VERSION="${VERSION_ARRAY[0]}.${NEW_MINOR}.0"
          echo "New Version: $NEW_VERSION"

          perl -i -pe "s/var GATESENTRY_VERSION = \"[0-9]+\.[0-9]+\.[0-9]+\"/var GATESENTRY_VERSION = \"$NEW_VERSION\"/" main.go
          PERL_EXIT_CODE=$?
          echo "Perl Exit Code: $PERL_EXIT_CODE"

          cat main.go  # This will output the contents of main.go to the log, so you can verify the substitution

          echo "::set-output name=new-version::$NEW_VERSION"

      - name: Commit and tag
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add main.go
          git commit -m "Bump version to ${{ steps.bump-version.outputs.new-version }}"
          git push origin master
