name: Merge Bot

on:
  pull_request:
    types:
      - labeled
      - synchronize
      - unlabeled

jobs:
  merge:
    runs-on: ubuntu-latest
    name: Merge
    steps:
      - name: Integration check
        uses: squalrus/merge-bot@v0.1.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          test: true
          reviewers: true
          labels: ready, merge
          blocking_labels: do not merge
          checks_enabled: true
          method: squash
          delete_source_branch: true
